//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocaizableProject.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_hi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_hi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocaizableProject.Resources.Views.Home.Index.hi", typeof(Index_hi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पता.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आयु.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to संपर्क करें प्रपत्र.
        /// </summary>
        internal static string Contact_Form {
            get {
                return ResourceManager.GetString("Contact Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://zeevector.com/wp-content/uploads/2020/05/Bajaj-Finserv-Logo-PNG-387x258.png.
        /// </summary>
        internal static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नाम.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जमा करना.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to राइटिंग लाइफ पॉडकास्ट लिखने वाले किसी भी व्यक्ति के लिए पॉडकास्ट है। हर पखवाड़े, हम आपके लेखन को थीम, संरचना और दिनचर्या से लेकर भाषा, चरित्र और लेखन विशिष्ट शैलियों तक बेहतर बनाने में मदद करने के लिए लेखकों और शिक्षकों से बात करते हैं।.
        /// </summary>
        internal static string The_Writing_Life_podcast_is_the_podcast_for_anyone_who_writes__Every_fortnight__we_speak_to_writers_and_educators_to_help_you_improve_your_writing__from_theme__structure_and_routine_to_language__character_and_writing_specific_genres_ {
            get {
                return ResourceManager.GetString("The Writing Life podcast is the podcast for anyone who writes. Every fortnight, w" +
                        "e speak to writers and educators to help you improve your writing, from theme, s" +
                        "tructure and routine to language, character and writing specific genres.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  स्वागत.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
