//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocaizableProject.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HomeController_mr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeController_mr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocaizableProject.Resources.Controllers.HomeController.mr", typeof(HomeController_mr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to द रायटिंग लाइफ पॉडकास्ट हे लिहिणाऱ्या प्रत्येकासाठी पॉडकास्ट आहे. दर पंधरवड्याला, आम्ही लेखक आणि शिक्षकांशी बोलतो जे तुम्हाला तुमचे लेखन सुधारण्यासाठी, थीम, रचना आणि दिनचर्यापासून भाषा, वर्ण आणि लेखन विशिष्ट शैलींमध्ये मदत करण्यासाठी बोलतो..
        /// </summary>
        internal static string The_Writing_Life_podcast_is_the_podcast_for_anyone_who_writes__Every_fortnight__we_speak_to_writers_and_educators_to_help_you_improve_your_writing__from_theme__structure_and_routine_to_language__character_and_writing_specific_genres_ {
            get {
                return ResourceManager.GetString("The Writing Life podcast is the podcast for anyone who writes. Every fortnight, w" +
                        "e speak to writers and educators to help you improve your writing, from theme, s" +
                        "tructure and routine to language, character and writing specific genres.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कंट्रोलर कडून स्वागत.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
